version: 2.1

jobs:
  build:
    working_directory: ~/simple_tables/tables
    docker:
      - image: cimg/rust:1.56.0
    steps:
      - checkout:
            path: ~/simple_tables
      - run: find .
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
